//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServices.CSharp.MercuryWebServices {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.mercurypay.com", ConfigurationName="MercuryWebServices.wsSoap")]
    public interface wsSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CBatch", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet CBatch(string merchant);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/AllowRunAsDebit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AllowRunAsDebit(string merchant, string pw, string account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CTranDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CTranDetail(string merchant, string pw, string invoice);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CAllDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CAllDetail(string merchant, string pw, string invoice, string startdate, string enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CAllDetailEx", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CAllDetailEx(string merchant, string pw, string invoice, string startdate, string enddate, string transactioncode);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CAllGiftDetail", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CAllGiftDetail(string merchant, string pw, string invoice, string startdate, string enddate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/CreditTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string CreditTransaction(string tran, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/GiftTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GiftTransaction(string tran, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/LoyaltyTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string LoyaltyTransaction(string tran, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/AssociateAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool AssociateAccount(string account, string identifier, string merchantid, string memo, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/RemoveAccountAssociation", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        bool RemoveAccountAssociation(string account, string identifier, string merchantid, string pw);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.mercurypay.com/Lookup", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Lookup(string tran, string pw);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface wsSoapChannel : WebServices.CSharp.MercuryWebServices.wsSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class wsSoapClient : System.ServiceModel.ClientBase<WebServices.CSharp.MercuryWebServices.wsSoap>, WebServices.CSharp.MercuryWebServices.wsSoap {
        
        public wsSoapClient() {
        }
        
        public wsSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public wsSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public wsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet CBatch(string merchant) {
            return base.Channel.CBatch(merchant);
        }
        
        public bool AllowRunAsDebit(string merchant, string pw, string account) {
            return base.Channel.AllowRunAsDebit(merchant, pw, account);
        }
        
        public string CTranDetail(string merchant, string pw, string invoice) {
            return base.Channel.CTranDetail(merchant, pw, invoice);
        }
        
        public string CAllDetail(string merchant, string pw, string invoice, string startdate, string enddate) {
            return base.Channel.CAllDetail(merchant, pw, invoice, startdate, enddate);
        }
        
        public string CAllDetailEx(string merchant, string pw, string invoice, string startdate, string enddate, string transactioncode) {
            return base.Channel.CAllDetailEx(merchant, pw, invoice, startdate, enddate, transactioncode);
        }
        
        public string CAllGiftDetail(string merchant, string pw, string invoice, string startdate, string enddate) {
            return base.Channel.CAllGiftDetail(merchant, pw, invoice, startdate, enddate);
        }
        
        public string CreditTransaction(string tran, string pw) {
            return base.Channel.CreditTransaction(tran, pw);
        }
        
        public string GiftTransaction(string tran, string pw) {
            return base.Channel.GiftTransaction(tran, pw);
        }
        
        public string LoyaltyTransaction(string tran, string pw) {
            return base.Channel.LoyaltyTransaction(tran, pw);
        }
        
        public bool AssociateAccount(string account, string identifier, string merchantid, string memo, string pw) {
            return base.Channel.AssociateAccount(account, identifier, merchantid, memo, pw);
        }
        
        public bool RemoveAccountAssociation(string account, string identifier, string merchantid, string pw) {
            return base.Channel.RemoveAccountAssociation(account, identifier, merchantid, pw);
        }
        
        public string Lookup(string tran, string pw) {
            return base.Channel.Lookup(tran, pw);
        }
    }
}
